FROM ubuntu:14.04
MAINTAINER John Wooten <jwooten@cloudconsulted.com>

ENV HOME /root
ADD . /build

RUN /build/prepare.sh && \
	/build/system_services.sh && \
	/build/utilities.sh && \
	/build/cleanup.sh

CMD ["/sbin/my_init"]
